### ISSUE TITLE
"Back" button should bring you to the main page of the app

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#187] opened 2021-06-14 14:43 UTC
**Describe the bug**
"Back" button should bring you to the main page of the app instead to the previous url visited.

**To Reproduce**
1. Go to `https://circles.garden/profile/<a-profile-address>`
2. Click on the arrow button place on the top-left corner

**Expected behavior**
I expect being redirected to `https://circles.garden`.

**Comment by louilinn** [comment] 2023-10-10 14:58
Closed as duplicate of https://github.com/CirclesUBI/circles-myxogastria/issues/565

**Closed as completed by louilinn** 2023-10-10 14:58 UTC
Labels: good first issue :heart:, confusion :confused:, help wanted :heart:, a priority ★★☆
