### ISSUE TITLE
The share profile link button has disappeared from the validation view

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#586] opened 2023-01-25 09:54 UTC
The share profile link has disappeared from the validation view.
Is this caused by the banner of Account Creation error?

**Comment by mikozet** [comment] 2023-01-26 06:40
Could you write more details @llunaCreixent ? Device and browser?
I cannot replicate it...
![Screenshot from 2023-01-26 10-38-59](https://user-images.githubusercontent.com/95082155/214773025-ad2a9f09-d23d-44c0-97f7-61943cddd17d.png)

**Comment by louilinn** [comment] 2023-02-13 11:30
First we have to see if we can reproduce in local dev

Bug fix:
branch PR off main 
merge with release later

**Comment by louilinn** [comment] 2023-03-02 08:31
Clearification:
Share profile button disappears when 3 trusts are reached and you can create your account. I'm quite sure this is the intended behavior :)
Can I close this issue? @llunaCreixent 

![Screenshot from 2023-03-02 09-29-56](https://user-images.githubusercontent.com/20553836/222373979-5f661c6f-fe0c-49ab-810f-e2622ac6e0a0.png)
![Screenshot from 2023-03-02 09-29-01](https://user-images.githubusercontent.com/20553836/222373987-23710697-50f0-4b3c-9c12-7d7fc2462fef.png)

**Closed as not planned** 2023-03-06 11:43 UTC
Labels: bug :boom:
