### ISSUE TITLE
Re-design of the Validation process  

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#417] opened 2022-06-23 14:11 UTC
We are gonna displayed the profile info of each trust connection a wallet gets during validation process. 

**Design Material** https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A42078

**Comment by louilinn** [comment] 2022-07-01 11:20
https://github.com/CirclesUBI/circles-core/issues/124

**Comment by louilinn** [comment] 2022-07-01 11:22
Duplicate of this https://github.com/CirclesUBI/circles-myxogastria/issues/325

**Closed as completed by louilinn** 2022-07-01 11:22 UTC
Labels: enhancement :sparkler:, a priority ★★★
